#!/bin/bash

# 🔑 Quick GitHub Secrets Setup Guide
echo "🔑 GitHub Secrets Quick Setup"
echo "============================="
echo ""
echo "🔗 GitHub Secrets URL:"
echo "https://github.com/JohnnyButtersfingers/hamlite-web3-dodgeball/settings/secrets/actions"
echo ""
echo "📋 Copy these exact secret names:"
echo ""
echo "1. VERCEL_TOKEN"
echo "2. VITE_ABS_RPC_URL"
echo "3. VITE_PINATA_API_KEY"
echo "4. VITE_PINATA_SECRET_API_KEY"
echo "5. VITE_AIRTABLE_API_KEY"
echo "6. VITE_AIRTABLE_BASE_ID"
echo ""
echo "💡 Values to use:"
echo ""
echo "VITE_ABS_RPC_URL = https://rpc.abstract.xyz"
echo "VERCEL_TOKEN = [Your new Vercel token]"
echo "VITE_PINATA_API_KEY = [Your new Pinata API key]"
echo "VITE_PINATA_SECRET_API_KEY = [Your new Pinata secret]"
echo "VITE_AIRTABLE_API_KEY = [Your new Airtable token]"
echo "VITE_AIRTABLE_BASE_ID = [Your Airtable base ID]"
echo ""
echo "⚠️  REMEMBER: Use only NEW, regenerated API keys!"
echo ""
echo "🚀 After adding secrets, test with:"
echo "git add ."
echo "git commit -m 'test: trigger deployment'"
echo "git push origin main"
echo ""
echo "📊 Monitor at:"
echo "https://github.com/JohnnyButtersfingers/hamlite-web3-dodgeball/actions"
